// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.ut.ags.domain;

import ee.ut.ags.domain.SimulationResult;
import ee.ut.ags.domain.SimulationResultDataOnDemand;
import ee.ut.ags.domain.SimulationResultIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SimulationResultIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SimulationResultIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SimulationResultIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SimulationResultIntegrationTest: @Transactional;
    
    @Autowired
    private SimulationResultDataOnDemand SimulationResultIntegrationTest.dod;
    
    @Test
    public void SimulationResultIntegrationTest.testCountSimulationResults() {
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to initialize correctly", dod.getRandomSimulationResult());
        long count = SimulationResult.countSimulationResults();
        Assert.assertTrue("Counter for 'SimulationResult' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SimulationResultIntegrationTest.testFindSimulationResult() {
        SimulationResult obj = dod.getRandomSimulationResult();
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to provide an identifier", id);
        obj = SimulationResult.findSimulationResult(id);
        Assert.assertNotNull("Find method for 'SimulationResult' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SimulationResult' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SimulationResultIntegrationTest.testFindAllSimulationResults() {
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to initialize correctly", dod.getRandomSimulationResult());
        long count = SimulationResult.countSimulationResults();
        Assert.assertTrue("Too expensive to perform a find all test for 'SimulationResult', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SimulationResult> result = SimulationResult.findAllSimulationResults();
        Assert.assertNotNull("Find all method for 'SimulationResult' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SimulationResult' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SimulationResultIntegrationTest.testFindSimulationResultEntries() {
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to initialize correctly", dod.getRandomSimulationResult());
        long count = SimulationResult.countSimulationResults();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SimulationResult> result = SimulationResult.findSimulationResultEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SimulationResult' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SimulationResult' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SimulationResultIntegrationTest.testFlush() {
        SimulationResult obj = dod.getRandomSimulationResult();
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to provide an identifier", id);
        obj = SimulationResult.findSimulationResult(id);
        Assert.assertNotNull("Find method for 'SimulationResult' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySimulationResult(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SimulationResult' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SimulationResultIntegrationTest.testMergeUpdate() {
        SimulationResult obj = dod.getRandomSimulationResult();
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to provide an identifier", id);
        obj = SimulationResult.findSimulationResult(id);
        boolean modified =  dod.modifySimulationResult(obj);
        Integer currentVersion = obj.getVersion();
        SimulationResult merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SimulationResult' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SimulationResultIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to initialize correctly", dod.getRandomSimulationResult());
        SimulationResult obj = dod.getNewTransientSimulationResult(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SimulationResult' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SimulationResult' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SimulationResultIntegrationTest.testRemove() {
        SimulationResult obj = dod.getRandomSimulationResult();
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SimulationResult' failed to provide an identifier", id);
        obj = SimulationResult.findSimulationResult(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SimulationResult' with identifier '" + id + "'", SimulationResult.findSimulationResult(id));
    }
    
}
