// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.ut.ags.domain;

import ee.ut.ags.domain.SimulationResult;
import ee.ut.ags.domain.SimulationResultDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SimulationResultDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SimulationResultDataOnDemand: @Component;
    
    private Random SimulationResultDataOnDemand.rnd = new SecureRandom();
    
    private List<SimulationResult> SimulationResultDataOnDemand.data;
    
    public SimulationResult SimulationResultDataOnDemand.getNewTransientSimulationResult(int index) {
        SimulationResult obj = new SimulationResult();
        setEndTime(obj, index);
        setSomething(obj, index);
        return obj;
    }
    
    public void SimulationResultDataOnDemand.setEndTime(SimulationResult obj, int index) {
        Calendar endTime = Calendar.getInstance();
        obj.setEndTime(endTime);
    }
    
    public void SimulationResultDataOnDemand.setSomething(SimulationResult obj, int index) {
        String something = "something_" + index;
        obj.setSomething(something);
    }
    
    public SimulationResult SimulationResultDataOnDemand.getSpecificSimulationResult(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SimulationResult obj = data.get(index);
        Long id = obj.getId();
        return SimulationResult.findSimulationResult(id);
    }
    
    public SimulationResult SimulationResultDataOnDemand.getRandomSimulationResult() {
        init();
        SimulationResult obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SimulationResult.findSimulationResult(id);
    }
    
    public boolean SimulationResultDataOnDemand.modifySimulationResult(SimulationResult obj) {
        return false;
    }
    
    public void SimulationResultDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SimulationResult.findSimulationResultEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SimulationResult' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SimulationResult>();
        for (int i = 0; i < 10; i++) {
            SimulationResult obj = getNewTransientSimulationResult(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
